substitutions:
  node_name: "hvac-master-bedroom"
  friendly_name: "AC Master Bedroom"

packages:
  hvac_remote: github://bertique/esphome-mitsubishi-hvac-base/hvac_base.yaml@main

wifi:
 # use_address: "jacobs-bedroom.local"
