substitutions:
  node_name: "hvac-familyroom"
  friendly_name: "AC Family Room"
  my_ssid: !secret wifi_ssid
  my_password: !secret  wifi_password

packages:
  hvac_remote: github://bertique/esphome-mitsubishi-hvac-base/hvac_base.yaml@main
